NAME = so_long
CC = gcc
CFLAGS =  -Wall -Wextra -Werror

SRCS_DIR = src
OBJS_DIR = objs
INCLUDES = -Iinclude -Ilib

SRCS = $(addprefix &(SCRS_DIR)/, main.c other_files.c)
OBJS = $(SRCS:&(SRCS_DIR)/&.c=$(OBJS_DIR)/%.o)

LIBMLX = lib/libmlx.a
LIBS = LIBS = -Llib -lmlx -lX11 -lXext -lm -lbsd
LIBFT = lib/libft.a

all: $(NAME)

$(NAME): $(OBJS) $(LIBMLX)
	$(CC) $(CFLAGS) $(OBJS) $(LIBS) -o $(NAME)

$(OBJS_DIR)/%.o: $(SRCS_DIR)/%.c
	mkdir -p $(OBJS_DIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -rf $(OBJS_DIR)

fclean: clean
	rm -f $(NAME)

re: fclean all